In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

%matplotlib inline

In [ ]:
def Logistic(t,K,r,C0):
  return K/(1+(K/C0-1)*np.exp(-r*t))


def tc(K,r,C0):
  return (1/r)*np.log(K/C0-1)

def tjp(K,r,C0):
  return (1/r)*np.log((K/C0-1)/(2-(3)**(1/2)))

def tjm(K,r,C0):
  return (1/r)*np.log((K/C0-1)/(2+(3)**(1/2)))

def ts(K,r,C0):
  return (1/r)*np.log((K/C0-1)/(5-2*(6)**(1/2)))


In [ ]:
List = []
for i in range(500):
  tf = np.random.randint(20,50)
  r = 0.02*np.random.random_sample() + 0.3
  K = 10000 + 2000*np.random.random_sample()
  C0=1 
  Tjm = round(tjm(K,r,C0))
  Tc = round(tc(K,r,C0))
  Tjp = round(tjp(K,r,C0))
  Ts = round(ts(K,r,C0))
  Cf = Logistic(tf,K,r,C0)
  Ch = Logistic(tf/2,K,r,C0)
  Cq = Logistic(0.25*tf,K,r,C0)
  C3q = Logistic(0.75*tf,K,r,C0)
  if tf < Tjm:
    sit = 'Aceleração crescente'
  if tf>=Tjm and tf<Tc:
    sit = 'Aceleração decrescente'
  if tf>=Tc and tf<Tjp:
    sit = 'Desaceleração crescente'
  if tf>=Tjp and tf<Ts:
    sit = 'Transição para saturação'
  if tf >= Ts:
    sit = 'Saturação'
  #print(K, r, Tc, round(tf/2), Ch/Cf, tf, Cf/Cf, sit)
  #print(Tjm,Tc,Tjp,Ts, tf, Cq/Cf, Ch/Cf, C3q/Cf, sit)
  element_list = {'quarter': Cq/Cf, 'half': Ch/Cf, 'third-quarter': C3q/Cf, 'sit': sit}
  List.append(element_list)

In [ ]:
df = pd.DataFrame(List)
print(df['sit'].value_counts())
print(df.shape)

Saturação                   212
Aceleração crescente         96
Aceleração decrescente       70
Desaceleração crescente      70
Transição para saturação     52
Name: sit, dtype: int64
(500, 4)


In [ ]:
feature_names = ['quarter','half', 'third-quarter']
X = df[feature_names]
y = df['sit']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(logreg.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(logreg.score(X_test, y_test)))

Accuracy of Logistic regression classifier on training set: 0.63
Accuracy of Logistic regression classifier on test set: 0.56


In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.98


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 0.98
Accuracy of K-NN classifier on test set: 0.98


In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[30  1  0  0  0]
 [ 0 21  0  0  0]
 [ 0  0 23  0  0]
 [ 0  0  0 39  0]
 [ 0  0  0  2  9]]
                          precision    recall  f1-score   support

    Aceleração crescente       1.00      0.97      0.98        31
  Aceleração decrescente       0.95      1.00      0.98        21
 Desaceleração crescente       1.00      1.00      1.00        23
               Saturação       0.95      1.00      0.97        39
Transição para saturação       1.00      0.82      0.90        11

                accuracy                           0.98       125
               macro avg       0.98      0.96      0.97       125
            weighted avg       0.98      0.98      0.98       125



In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = clf.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[30  1  0  0  0]
 [ 1 20  0  0  0]
 [ 0  0 23  0  0]
 [ 0  0  0 39  0]
 [ 0  0  0  1 10]]
                          precision    recall  f1-score   support

    Aceleração crescente       0.97      0.97      0.97        31
  Aceleração decrescente       0.95      0.95      0.95        21
 Desaceleração crescente       1.00      1.00      1.00        23
               Saturação       0.97      1.00      0.99        39
Transição para saturação       1.00      0.91      0.95        11

                accuracy                           0.98       125
               macro avg       0.98      0.97      0.97       125
            weighted avg       0.98      0.98      0.98       125



In [ ]:
print(np.random.random_sample())

print(np.random.randn())

0.10044103542628835
-1.0009761802547297


In [ ]:
print(tc(10000,0.3,1))

30.70080122325283
